Repository mmschlk/shapiq, pull requests merged in 2024-04, with the labels that each got.

#91 Make Example Notebooks Available in the Docs
  docs/source/index.rst
  docs/source/notebooks/bike.ipynb
  docs/source/notebooks/example.py
  notebooks
Labels: documentation

#116 renames indices and adds a configuration file (closes #83)
  docs/source/api.rst
  docs/source/notebooks/bike.ipynb
  illustration_sources/uml_shapiq.drawio
  shapiq/__init__.py
  shapiq/approximator/__init__.py
  shapiq/approximator/_base.py
  shapiq/approximator/_config.py
  shapiq/approximator/moebius_converter.py
  shapiq/approximator/permutation/__init__.py
  shapiq/approximator/permutation/stii.py
  shapiq/approximator/regression/__init__.py
  shapiq/approximator/regression/_base.py
  shapiq/approximator/regression/fsi.py
  shapiq/approximator/regression/sv.py
  shapiq/approximator/sampling.py
  shapiq/approximator/shapiq/shapiq.py
  shapiq/exact.py
  shapiq/explainer/tabular.py
  shapiq/explainer/tree/treeshapiq.py
  shapiq/indices.py
  shapiq/interaction_values.py
  shapiq/utils/__init__.py
  shapiq/utils/modules.py
  tests/test_base_interaction_values.py
  tests/test_configuration.py
  tests/test_exact_computer.py
  tests/test_integration_import_all.py
  tests/tests_approximators/test_approximator_moebius_converter.py
  tests/tests_approximators/test_approximator_permutation_sti.py
  tests/tests_approximators/test_approximator_regression_fsi.py
  tests/tests_approximators/test_approximator_regression_sv.py
  tests/tests_approximators/test_approximator_shapiq.py
  tests/tests_approximators/test_approximator_unbiased_ksh.py
  tests/tests_explainer/test_explainer_tabular.py
  tests/tests_explainer/tests_tree_explainer/test_tree_treeshapiq.py
  tests/tests_utils/test_utils_modules.py
Labels: enhancement

#121 adds Dataset Valuation games as Benchmark games.
  shapiq/games/benchmark/valuation.py
  shapiq/games/valuation.py
  shapiq/utils/__init__.py
  shapiq/utils/datasets.py
  tests/tests_games/test_valuation_game.py
Labels: enhancement

#123 96 add permutation sampling for sv
  illustration_sources/uml_shapiq.svg
  shapiq/approximator/__init__.py
  shapiq/approximator/permutation/__init__.py
  shapiq/approximator/permutation/sv.py
  tests/tests_approximators/test_approximator_permutation_sv.py
Labels: enhancement

#142 Fixes the Unsupervised Data Benchmark Game.
  shapiq/games/benchmark/unsupervised_data/base.py
  tests/tests_games/test_unsupervised_data.py
Labels: games
